name: testMiniGame2
displayNameKey: games.testMiniGame2.displayName
descriptionKey: games.testMiniGame2.description
guiBlock: SAND
public: true
permission: some.not-available.permission.key
minPlayers: 1
maxPlayers: 8
minGroupSize: 1
maxGroupSize: 8


gameConfig:
  worlds:
    - name: world4
      enabled: true
      displayNameKey: games.testMiniGame2.worlds.world4.displayName
      maxPlayers: 4
      minPlayers: 1
      spawnPoints:
        - x: -42 # red
          y: 35
          z: -85
          yaw: 1
          pitch: 1
        - x: -42 # green
          y: 35
          z: 81
          yaw: 179
          pitch: 1
        - x: 43 # yellow
          y: 35
          z: 81
          yaw: -179
          pitch: -1
        - x: 43 # blue
          y: 35
          z: -83
          yaw: 0
          pitch: -1

    - name: world8
      enabled: true
      displayNameKey: games.testMiniGame2.worlds.world8.displayName
      maxPlayers: 8
      minPlayers: 1
      spawnPoints:
        - x: -77 # dark_blue
          y: 29
          z: -27
          yaw: -86
          pitch: -1
        - x: -30 # green
          y: 29
          z: -74
          yaw: 1
          pitch: 0
        - x: 37 # yellow
          y: 29
          z: -75
          yaw: 1
          pitch: 1
        - x: 84 # blue
          y: 29
          z: -27
          yaw: 89
          pitch: 3
        - x: 84 # white
          y: 29
          z: 40
          yaw: 91
          pitch: 3
        - x: 37 # pink
          y: 29
          z: 87
          yaw: 178
          pitch: 0
        - x: -30 # gray
          y: 29
          z: 87
          yaw: 179
          pitch: 0
        - x: -77 # red
          y: 29
          z: 40
          yaw: -91
          pitch: 0
