name: testMiniGame
displayNameKey: games.testMiniGame.displayName
descriptionKey: games.testMiniGame.description
guiBlock: RED_SAND
public: true
permission: null
minPlayers: 1
maxPlayers: 8
minGroupSize: 1
maxGroupSize: 8


gameConfig:
  worlds:
    - name: "4"
      enabled: true
      displayNameKey: games.testMiniGame.worlds.world4.displayName
      maxPlayers: 4
      minPlayers: 1
      spawnPoints:
        - x: -42 # red
          y: 35
          z: -85
          facingX: 1
          facingZ: 1
        - x: -42 # green
          y: 35
          z: 81
          facingX: 179
          facingZ: 1
        - x: 43 # yellow
          y: 35
          z: 81
          facingX: -179
          facingZ: -1
        - x: 43 # blue
          y: 35
          z: -83
          facingX: 0
          facingZ: -1

    - name: "8"
      enabled: true
      displayNameKey: games.testMiniGame.worlds.world8.displayName
      maxPlayers: 8
      minPlayers: 1
      spawnPoints:
        - x: -77 # dark_blue
          y: 29
          z: -27
          facingX: -86
          facingZ: -1
        - x: -30 # green
          y: 29
          z: -74
          facingX: 1
          facingZ: 0
        - x: 37 # yellow
          y: 29
          z: -75
          facingX: 1
          facingZ: 1
        - x: 84 # blue
          y: 29
          z: -27
          facingX: 89
          facingZ: 3
        - x: 84 # white
          y: 29
          z: 40
          facingX: 91
          facingZ: 3
        - x: 37 # pink
          y: 29
          z: 87
          facingX: 178
          facingZ: 0
        - x: -30 # gray
          y: 29
          z: 87
          facingX: 179
          facingZ: 0
        - x: -77 # red
          y: 29
          z: 40
          facingX: -91
          facingZ: 0