name: Docs
on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4.1.4
      - name: Setup java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: "21"
          check-latest: true
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3.3.2
        with:
          cache-read-only: false
      - name: Build docs
        run: ./gradlew --no-daemon --warning-mode=all --info --configuration-cache --build-cache dokkaHtmlCollector
      - name: Upload docs as an artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: dokka-${{ github.sha }}
          path: build/dokka/htmlCollector

  deploy_docs:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy docs
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: dokka-${{ github.sha }}
